spring:
  datasource:
    url: jdbc:mysql://39.104.173.18:3306/embryoai_acloud_db?characterEncoding=utf8
    username: root
    password: 123456
    initial-size: 5
    max-active: 200
    min-idle: 5
    max-idle: 100
    test-on-borrow: true
    min-evictable-idle-time-millis: 300
 
server:
  port: 8086
  

mybatis:
  mapper-locations:
  - classpath:mappings/**/*.xml